import type { Metadata } from "next";
import "./globals.css";
import { Noto_Sans } from "next/font/google";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Controle Facil",
  description: "Generated by CameloDev",
};

const noto = Noto_Sans({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  variable: "--font-noto",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${noto.variable} antialiased font-sans`}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
